import { createClient } from '@sanity/client'

const client = createClient({
  projectId: 'hbtavgd1',
  dataset: 'production',
  useCdn: false,
  apiVersion: '2024-01-01',
  token: process.env.SANITY_API_TOKEN,
})

const newsItems = [
  {
    _type: 'news',
    id: '1',
    date: '2025.10.14',
    title: '2025年11月2日・滝田洋二郎監督をお迎えしてトークイベントを開催いたします。',
    titleEn: 'Talk event with director Yoji Takita scheduled for November 2, 2025',
    category: 'event',
    excerpt: 'アカデミー賞受賞監督・滝田洋二郎氏をお招きし、映画と地域創生をテーマにしたトークイベントを開催します。',
    excerptEn: 'Academy Award-winning director Yoji Takita will join us for a talk event on film and regional revitalization.',
    content: 'アカデミー賞受賞監督・滝田洋二郎氏をお招きし、映画と地域創生をテーマにしたトークイベントを開催します。\n\n「おくりびと」「陰陽師」などの名作を生み出した滝田監督と、地域の物語を映像化することの意義と可能性について深く対話します。\n\n【日時】2025年11月2日（土）14:00〜16:00\n【場所】東京都内（詳細は申込者にお知らせします）\n【参加費】無料\n【定員】50名（先着順）',
    externalLink: 'https://myu-kamimusubi.jp/event/JhyvqjeM',
  },
  {
    _type: 'news',
    id: '2',
    date: '2025.09.24',
    title: '株式会社ライトコーポレーションと共同で「資本開発倶楽部」を設立しました。',
    titleEn: "Establishment of 'Capital Development Club' in partnership with Light Corporation",
    category: 'release',
    excerpt: '4つの資本（関係資本・地域資本・生命資本・循環資本）を統合的に開発する新しい事業モデルの研究・実践コミュニティを設立。',
    excerptEn: 'Established a new research and practice community for developing four types of capital: relational, regional, life, and circular capital.',
    content: '株式会社未来づくりカンパニーは、株式会社ライトコーポレーションと共同で「資本開発倶楽部」を設立いたしました。\n\n資本開発倶楽部は、従来の金融資本中心の考え方から脱却し、4つの資本（関係資本・地域資本・生命資本・循環資本）を統合的に開発する新しい事業モデルの研究・実践コミュニティです。',
    externalLink: 'https://prtimes.jp/main/html/rd/p/000000026.000066948.html',
  },
  {
    _type: 'news',
    id: '3',
    date: '2025.04.02',
    title: '『Anchor』4月号に弊社代表大羽とつまみ枝豆氏の対談記事が掲載されました。',
    titleEn: 'CEO Oba and Tsumami Edamame featured in Anchor magazine April issue',
    category: 'media',
    excerpt: 'ビジネス誌『Anchor』にて、代表・大羽昭仁とつまみ枝豆氏による対談「地域と笑いの力」が掲載されました。',
    excerptEn: "Business magazine 'Anchor' features a dialogue between CEO Akihito Oba and Tsumami Edamame on 'The Power of Regions and Laughter'.",
    content: 'ビジネス誌『Anchor』4月号にて、弊社代表・大羽昭仁とタレント・つまみ枝豆氏による対談記事「地域と笑いの力」が掲載されました。\n\nエンターテインメントと地域創生の接点、笑いが持つコミュニティの力について、ユーモアを交えながら深い議論を展開しています。',
    externalLink: 'https://miraidukuri.co.jp/38xp7a/wp-content/uploads/2025/04/anchor.pdf',
  },
  {
    _type: 'news',
    id: '4',
    date: '2025.02.25',
    title: 'ミトエール ECサイトにて「水戸献水」炭酸飲料の販売を開始しました。',
    titleEn: "Launch of 'Mitouken Water' carbonated beverage on Mito-yell e-commerce site",
    category: 'announcement',
    excerpt: '水戸の名水を使用した炭酸飲料「水戸献水」の販売をミトエールECサイトにて開始しました。',
    excerptEn: "Started selling 'Mitouken Water' carbonated beverage made with Mito's famous spring water on the Mito-yell e-commerce site.",
    externalLink: 'https://www.mitoyell.com',
  },
  {
    _type: 'news',
    id: '5',
    date: '2024.11.14',
    title: '赤坂に「未来へのごちそう gogo」がオープンしました。',
    titleEn: "Opening of 'Mirai e no Gochisou gogo' restaurant in Akasaka",
    category: 'announcement',
    excerpt: '地域の食材と生産者のストーリーを届けるレストラン「未来へのごちそう gogo」が赤坂にオープン。',
    excerptEn: "Restaurant 'Mirai e no Gochisou gogo', showcasing regional ingredients and producer stories, opens in Akasaka.",
    externalLink: 'https://mira-gochi.com',
  },
  {
    _type: 'news',
    id: '6',
    date: '2024.10.11',
    title: '鹿児島にて「薩摩サムライスピリットツアー」プログラムを販売開始。',
    titleEn: 'Satsuma Samurai Spirit Tour programs launched in Kagoshima',
    category: 'announcement',
    excerpt: '鹿児島の武士道精神と歴史文化を体験するツアープログラムの販売を開始しました。',
    excerptEn: 'Started sales of tour programs experiencing the samurai spirit and historical culture of Kagoshima.',
    externalLink: 'https://exp.miraidukuri.co.jp',
  },
  {
    _type: 'news',
    id: '7',
    date: '2024.10.02',
    title: '八戸圏域 食と祈りの体験プログラムを販売開始。',
    titleEn: 'Hachinohe region food and prayer experience program now available',
    category: 'announcement',
    excerpt: '八戸圏域の豊かな海産物と精神文化を体験するプログラムを日英両言語で提供開始。',
    excerptEn: "Experience programs for Hachinohe's rich seafood and spiritual culture now available in Japanese and English.",
    externalLink: 'https://exp.miraidukuri.co.jp',
  },
  {
    _type: 'news',
    id: '8',
    date: '2024.10.01',
    title: '臼杵市ガストロノミーツアープログラム（ユネスコ創造都市）を販売開始。',
    titleEn: 'Usuki City gastronomic tour program (UNESCO Creative City) launched',
    category: 'announcement',
    excerpt: 'ユネスコ創造都市・臼杵市の発酵文化と食を巡るガストロノミーツアーを開始。',
    excerptEn: 'Gastronomic tour exploring fermentation culture and cuisine in UNESCO Creative City Usuki.',
    externalLink: 'https://exp.miraidukuri.co.jp',
  },
  {
    _type: 'news',
    id: '9',
    date: '2024.08.31',
    title: '長野県にて縄文文化体験ツアーを販売開始。',
    titleEn: 'Jomon Era cultural tour in Nagano Prefecture now available',
    category: 'announcement',
    excerpt: '縄文時代の精神性と現代をつなぐ体験プログラムを長野県で展開開始。',
    excerptEn: 'Experience programs connecting Jomon era spirituality with modern times launched in Nagano Prefecture.',
    externalLink: 'https://exp.miraidukuri.co.jp',
  },
  {
    _type: 'news',
    id: '10',
    date: '2024.08.31',
    title: '多賀城市1300年記念 歴史体験プログラムを販売開始。',
    titleEn: 'Tagajo historical experience program for 1,300th anniversary launched',
    category: 'announcement',
    excerpt: '多賀城創建1300年を記念した歴史文化体験プログラムを日英両言語で提供。',
    excerptEn: '1,300 years of Tagajo, available in Japanese and English.',
    externalLink: 'https://exp.miraidukuri.co.jp',
  },
  {
    _type: 'news',
    id: '11',
    date: '2024.08.30',
    title: '琵琶湖サンセットクルーズ＆長浜手筒花火体験を販売開始。',
    titleEn: 'Lake Biwa sunset cruise with handmade fireworks in Nagahama launched',
    category: 'announcement',
    excerpt: '琵琶湖でのサンセットクルーズと長浜の伝統的な手筒花火を体験するプログラム。',
    excerptEn: 'Experience program combining a Lake Biwa sunset cruise with traditional Nagahama handmade fireworks.',
    externalLink: 'https://exp.miraidukuri.co.jp/biwako/',
  },
  {
    _type: 'news',
    id: '12',
    date: '2024.02.19',
    title: 'お茶とレモン go-go にてディナーコース＆飲み放題プランを開始。',
    titleEn: 'Dinner course with all-you-can-drink launched at Ocha to Lemon go-go',
    category: 'announcement',
    excerpt: '赤坂の「お茶とレモン go-go」にてディナーコースと飲み放題プランをスタート。',
    excerptEn: "Dinner course with all-you-can-drink plan started at 'Ocha to Lemon go-go' in Akasaka.",
    externalLink: 'https://go-go-akasaka.com/#menu',
  },
]

const projects = [
  {
    _type: 'project',
    id: { _type: 'slug', current: 'mito-yell' },
    title: '人と身体の結び直し―ミトエール',
    titleEn: 'Mito-yell',
    subtitle: 'ミトコンドリア活性化による健康・美容ブランド',
    subtitleEn: 'Health & Beauty Brand Powered by Mitochondria Activation',
    description: '再生医療・免疫療法の研究を基に開発された、ミトコンドリア活性化による健康と美容をサポートするウェルネスブランド。',
    descriptionEn: 'A wellness brand developed from regenerative medicine and immunotherapy research, supporting health and beauty through mitochondria activation.',
    fullDescription: 'Mito-yellは「科学と日常をつなぐ架け橋」をミッションに、ミトコンドリア機能のサポートを通じて健康最適化を目指すウェルネスブランドです。再生医療・免疫療法の研究成果を活かした飲料水やボディケア製品を展開。疲労回復、健康維持、アンチエイジング、運動効率向上など、ライフスタイルに寄り添った製品で、内側からの健康をサポートします。',
    fullDescriptionEn: "Mito-yell is a wellness brand with the mission of 'bridging science and daily life,' aiming to optimize health through mitochondrial function support.",
    domain: 'life',
    year: '2025',
    externalUrl: 'https://www.mitoyell.com/',
    tags: ['ミトコンドリア', '健康', '美容', 'ウェルネス', '再生医療'],
    tagsEn: ['Mitochondria', 'Health', 'Beauty', 'Wellness', 'Regenerative Medicine'],
    comingSoon: false,
  },
  {
    _type: 'project',
    id: { _type: 'slug', current: 'kamimusubi' },
    title: '人と神の結び直し―深結の神結び',
    titleEn: 'Myu-Kamimusubi',
    subtitle: '日本神話の叡智を現代に届けるファンコミュニティ',
    subtitleEn: 'A Fan Community Bringing Ancient Japanese Mythology to Modern Life',
    description: 'ヒーリングシンガー深結（ふかむす）を中心に、神話の語り、祈りの歌、神社巡りを通じて、自分らしい「結び」を見つけるコミュニティ。',
    descriptionEn: 'Centered around healing singer Miyū, a community for finding personal spiritual connections through mythology storytelling, sacred songs, and shrine pilgrimages.',
    domain: 'relational',
    year: '2025',
    externalUrl: 'https://myu-kamimusubi.jp/',
    tags: ['神話', 'スピリチュアル', 'コミュニティ', '音楽', '神社'],
    tagsEn: ['Mythology', 'Spiritual', 'Community', 'Music', 'Shrine'],
    comingSoon: false,
  },
  {
    _type: 'project',
    id: { _type: 'slug', current: 'mirai-gochiso' },
    title: '人と人、人と食の結び直し―未来へのごちそう',
    titleEn: 'MIRAI e no Gochiso',
    subtitle: '食べることが、未来をつくる。',
    subtitleEn: 'Eating Creates the Future.',
    description: 'お米を中心とした日本の食文化を復活させ、生産者・地域・地球との繋がりを通じて持続可能な食の未来を創造するレストラン。',
    descriptionEn: 'A restaurant reviving Japanese food culture centered on rice, creating a sustainable food future through connections with producers, regions, and the earth.',
    domain: 'life',
    year: '2024',
    externalUrl: 'https://mira-gochi.com/',
    tags: ['食', '持続可能性', '生産者支援', 'レストラン', '有機野菜'],
    tagsEn: ['Food', 'Sustainability', 'Producer Support', 'Restaurant', 'Organic'],
    comingSoon: false,
  },
  {
    _type: 'project',
    id: { _type: 'slug', current: 'container-farm' },
    title: '人と食の結び直し―自立型コンテナファーム',
    titleEn: 'Container Farm Project',
    subtitle: 'いつもの時ももしもの時も安心な食料生産システム',
    subtitleEn: 'A Reliable Food Production System for Everyday and Emergency',
    description: 'コンテナ型の垂直農法を活用し、都市部や過疎地域での食料自給率向上と防災機能を兼ね備えたシステムを構築。',
    descriptionEn: 'Building a system combining improved food self-sufficiency and disaster preparedness in urban and rural areas through container-based vertical farming.',
    domain: 'circular',
    year: '2025',
    tags: ['農業', 'テクノロジー', '防災'],
    tagsEn: ['Agriculture', 'Technology', 'Disaster Preparedness'],
    comingSoon: true,
  },
  {
    _type: 'project',
    id: { _type: 'slug', current: 'fan-community-business' },
    title: '人と人、人と地域の結び直し―ファンコミュニティビジネス',
    titleEn: 'Mirai Creation Experience',
    subtitle: '人と人が同じ価値で集まる場',
    subtitleEn: 'A Place Where People Gather Around Shared Values',
    description: '共通の価値観を持つ人々が集い、地域とつながるコミュニティビジネスモデル。',
    descriptionEn: 'A community business model where people with shared values gather and connect with local communities.',
    domain: 'relational',
    year: '2025',
    tags: ['コミュニティ', '地域', '関係性', 'ビジネスモデル'],
    tagsEn: ['Community', 'Regional', 'Relationships', 'Business Model'],
    comingSoon: true,
  },
  {
    _type: 'project',
    id: { _type: 'slug', current: 'japan-tea-action' },
    title: '人とお茶の結び直し―Japan Tea Action',
    titleEn: 'Japan Tea Action',
    subtitle: '日本茶業体制強化推進協議会',
    subtitleEn: 'Japan Tea Industry Promotion Council',
    description: '日本茶文化の普及と茶業の持続可能な発展を目指す全国プロジェクト。生産者と消費者を結ぶ新しいプラットフォームを構築。',
    descriptionEn: 'A nationwide project promoting Japanese tea culture and sustainable development of the tea industry, building new platforms connecting producers and consumers.',
    domain: 'life',
    year: '2020',
    externalUrl: 'https://japanteaaction.jp/',
    tags: ['日本茶', '健康', '伝統文化', 'コミュニティ'],
    tagsEn: ['Japanese Tea', 'Health', 'Traditional Culture', 'Community'],
    comingSoon: false,
  },
  {
    _type: 'project',
    id: { _type: 'slug', current: 'mibyou-project' },
    title: '人と身体の結び直し―未病息災プロジェクト',
    titleEn: 'Mibyo Sokusai Project',
    subtitle: 'ポジティブに人生を楽しみながら取り組む健康法',
    subtitleEn: 'A Positive Approach to Health While Enjoying Life',
    description: '「未病」とは「いまだ病ならざる」状態。放置すれば病気へ進行する可能性がありますが、食や運動、心身の健康づくりの自助努力で病気に煩わされない毎日を実現します。',
    descriptionEn: "'Mibyou' means a state of 'not yet ill.' Through self-care in diet, exercise, and mental wellness, we help achieve disease-free daily living before conditions progress.",
    domain: 'life',
    year: '2008',
    externalUrl: 'https://mibyo.org/',
    tags: ['未病', '健康寿命', '予防医療', '地域創生', 'ウェルネス'],
    tagsEn: ['Preventive Health', 'Healthy Longevity', 'Preventive Medicine', 'Regional Revitalization', 'Wellness'],
    comingSoon: false,
  },
  {
    _type: 'project',
    id: { _type: 'slug', current: 'designing-safety' },
    title: '人と危険の結び直し―Designing Safety',
    titleEn: 'Designing Safety',
    subtitle: '防犯・防災を自分でデザインする力を備える',
    subtitleEn: 'Connecting the Future Through Crime Prevention & Disaster Preparedness',
    description: '日常に潜む災害・犯罪のリスクに気づき、「気づく力」と「守る行動」を身につける安全教育プログラム。',
    descriptionEn: 'A safety education program that builds awareness of hidden risks from disasters and crime, developing the ability to notice and take protective action.',
    domain: 'life',
    year: '2025',
    externalUrl: 'https://designing-safety.com/',
    tags: ['防犯', '防災', '安全教育', '講座'],
    tagsEn: ['Crime Prevention', 'Disaster Preparedness', 'Safety Education', 'Course'],
    comingSoon: false,
  },
  {
    _type: 'project',
    id: { _type: 'slug', current: 'hisui-protection' },
    title: '人と地域の安全な結び直し―HISUI PROTECTION',
    titleEn: 'HISUI PROTECTION',
    subtitle: '世界に誇る、和の護り ― 心を満たす悠久の旅',
    subtitleEn: "Japan's Finest Protection — A Timeless Journey That Enriches the Soul",
    description: '特殊部隊教官による高度警護と、日本文化の本質に触れる高付加価値観光体験を融合した、富裕層向け新観光モデル。',
    descriptionEn: 'A new luxury tourism model combining elite security by special forces instructors with high-value cultural experiences touching the essence of Japanese culture.',
    domain: 'relational',
    year: '2025',
    externalUrl: 'https://hisuiprotection.com/',
    tags: ['警護', '富裕層', '日本文化', 'VIP', '観光'],
    tagsEn: ['Security', 'Luxury', 'Japanese Culture', 'VIP', 'Tourism'],
    comingSoon: false,
  },
  {
    _type: 'project',
    id: { _type: 'slug', current: 'act-gommishion' },
    title: '人と廃棄物を結び直す―ACT.GOMMISHION',
    titleEn: 'ACT.GOMMISHION',
    subtitle: '廃棄物から循環の発想でエネルギーを生み出す',
    subtitleEn: 'Generating Energy from Waste Through Circular Thinking',
    description: '廃棄物を資源として捉え直し、循環型のエネルギー生産を実現するプロジェクト。',
    descriptionEn: 'A project that reframes waste as a resource, realizing circular energy production.',
    domain: 'circular',
    year: '2025',
    tags: ['廃棄物', 'エネルギー', '循環'],
    tagsEn: ['Waste', 'Energy', 'Circular'],
    comingSoon: true,
  },
  {
    _type: 'project',
    id: { _type: 'slug', current: 'plastic-to-oil' },
    title: '人と廃棄物を結び直す―廃プラ油化装置',
    titleEn: 'Mobile Plastic-to-Oil System',
    subtitle: '走りながら、未来をつくる',
    subtitleEn: 'Creating the Future on the Move',
    description: '廃プラスチックを地域内で油化・エネルギー化する移動式インフラ。廃棄物問題とエネルギー問題を同時に解決。',
    descriptionEn: 'A mobile infrastructure that converts waste plastic into oil and energy locally, solving both waste and energy problems simultaneously.',
    domain: 'circular',
    year: '2026',
    tags: ['廃棄物', 'エネルギー', '移動式', '循環', '2026年稼働'],
    tagsEn: ['Waste', 'Energy', 'Mobile', 'Circular', 'Launching 2026'],
    comingSoon: true,
  },
  {
    _type: 'project',
    id: { _type: 'slug', current: 'mirai-experience' },
    title: '人と地域の結び直し―未来づくりエクスペリエンス',
    titleEn: 'Mirai Creation Experience',
    subtitle: '地域が持っている日本の素晴らしさと繋がる旅',
    subtitleEn: 'A Journey Connecting with the Wonders of Japan Through Local Communities',
    description: '従来の観光を再定義し、対話型体験プログラムを通じて自分の未来へのヒントを見つける体験を提供。',
    descriptionEn: 'Redefining conventional tourism, providing experiences that help discover hints for your future through interactive dialogue programs.',
    domain: 'regional',
    year: '2021',
    externalUrl: 'https://exp.miraidukuri.co.jp/en/',
    tags: ['体験', '観光', '対話', '未来づくり'],
    tagsEn: ['Experience', 'Tourism', 'Dialogue', 'Future Creation'],
    comingSoon: false,
  },
]

async function importData() {
  console.log('Importing news...')
  for (const item of newsItems) {
    await client.create(item)
    console.log(`✓ ${item.title}`)
  }

  console.log('\nImporting projects...')
  for (const item of projects) {
    await client.create(item)
    console.log(`✓ ${item.title}`)
  }

  console.log('\n✅ Done!')
}

importData().catch(console.error)